### PR TITLE
Two cases in patreon authorization and flow are covered with error messages against unlikely errors

### PR DESCRIPTION
**Pull request by codebard**
**Problem**

There are 2 cases in routing/authorization class which are not covered by error messages. This leads to some creators complaining about users going through the unlock flow but nothing happening when these cases trigger.

One case is a user being redirected to /patreon-authorization/ slug/page without any proper authorization code return from Patreon. This can happen when Patreon doesnt return any code due to any particular reason, the WP website loses the code in between redirects (especially redirection plugins, or security setups like overzealous mod_security, or security plugins may be culprits) or any other unknown setup at a particular WP site. 

The second case is when a user is directed to /patreon-flow/ slug/page without any request like unlock-post or login. This can end up happening due to similar reasons like the above. 

Result is user being directed to the page s/he started from or the main page without any message or notification without the post or content being unlocked. Which then leads to a perception of the plugin 'not working', which then leads to support incidents.

**Solution**

These simple changes add 2 error messages to these conditions and redirects the users to wp-login page in order to display the error message. 

**Verification**

UAC done, works. It can be reproduced by simply visiting domain.com/patreon-flow/ and domain.com/patreon-authorization/ pages by directly putting the urls in the browser bar in a site where this branch is installed. The 2 different messages are included in screenshots below.

message-1

message-2

**Does this need tests**

UAC was already done, and confirmed to work. There is no unit test written for this change or relevant functions at this time.

### CODE REVIEW

**Comment by spencerhandley** [comment]
In General, we want to lead the user to the next correct action. This is a dead end for the user. What should they do instead?

**Comment by spencerhandley** [comment]
I'm very curious how we get into this state ```his can happen when Patreon doesnt return any code due to any particular reason, the WP website loses the code in between redirects (especially redirection plugins, or security setups like overzealous mod_security, or security plugins may be culprits) or any other unknown setup at a particular WP site.```

**Comment by codebard** [comment]
Leading the user to correct action is always a splendid idea.  If we had extensive documentation already facing public, normally we would link them there. Like a faq, or a list of error messages with codes/numbers and their potential causes. Since we dont have it yet, we can link it to the plugin page we have at Patreon for now, and then when we have more solid stuff, we can change it.

Technically anything that snips the variables that are being sent in the return can cause that. Some potential causes:

(occasional) Any kind of redirection setup due to seo url changes, domain changes/moves, misconfigured login modification plugins (similar to Theme My Login - but it doesnt do that), misconfigured security plugins, any other plugin interfering with login/redirects, misconfigurations or forgotten exceptions in redirect plugins. 

(rare) Stringent security setups like mod_security in small 3rd party hosts. (rare, but more likely) same situation in small VPSes set by designers/developers who provide entry/mid level development/hosting services. 

The catch of the matter is that there are these 2 cases in flow and login which are not covered by messages. Logically we need to cover them regardless of the likeliness of the situation. That we are having a noticeable number of 'I unlock/login but nothing happens' requests only stresses this need.

**Comment by spencerhandley** [comment]
Ok, this feels like an ok solution for now, but would you mind outlining here what the more robust solution would look like, and then throwing that into a trello (soon to be jira) ticket for later prioritization? 

Once the conflicts are resolved, feel free to merge

**Comment by codebard** [comment]
A better solution would involve refactoring of previously created large functions that govern interface generation (even though they were already broken down into some components in the past months) and handling of such non-post content/elements accordingly. But at the moment this solution can take us a long way. I have posted a card in trello to remind this for medium term.

**Pull request merged**
