### PR TITLE
Added hook to rest_api_init to register metadata for use in REST

### PR DESCRIPTION
**Pull request by TamedTornado**
I'm using this patch in production and would greatly appreciate if it were rolled into your core. It allows you to read and write the two important patreon variables from REST, which helps my work flow with Patreon a lot.

### CODE REVIEW

**Comment by TamedTornado** [comment]
This successfully address issue #100

**Comment by codebard** [comment]
Since the hooked function included in this PR can be included from any plugin or theme, there isnt a need to merge this into plugin's own code directly. Despite the PR is much appreciated, i will close this due to that reason.

**Comment by wifiuk** [comment]
how are you changing the Patreon level per post via API, would be good to know?

**Comment by wifiuk** [comment]
> Since the hooked function included in this PR can be included from any plugin or theme, there isnt a need to merge this into plugin's own code directly. Despite the PR is much appreciated, i will close this due to that reason.

please explain how to add this to own theme if you are not going to include it in your plugin.

**Pull request closed without merging**
